Test typescript tictactoe
undesicimo/react-typescript-tictactoe pull request #2
Opened 2023-02-14 07:03 UTC by undesicimo

2023-02-14 07:53 UTC, hosht requested changes

2023-02-14 07:53 UTC, hosht commented on src/components/Game.test.tsx
> +        const user = userEvent.setup();
should: ほぼ全てのテストケースで使われている処理は共通化することでテストコードをテスト対象のみに集中させることができるので試してみましょう！
https://jestjs.io/docs/setup-teardown#repeating-setup

2023-02-14 07:53 UTC, hosht commented on package.json
> +    "@testing-library/user-event": "^14.4.3"
question: devDependenciesに移動したのはこちらの3つのライブラリですが、この3つを選び他はそのままにしているのはどのようなことを考えて移動しましたか？

2023-02-14 08:27 UTC, undesicimo commented on src/components/Game.test.tsx
> +        const user = userEvent.setup();
@hosht 
以下を確認したところ、setupの操作は、`before/after hook`で行うことが推奨されていないことがわかりました。
```
. We discourage rendering or using any userEvent functions outside of the test itself - e.g. in a before/after hook - for reasons described in ["Avoid Nesting When You're Testing"](https://kentcdodds.com/blog/avoid-nesting-when-youre-testing).
```
documentationにて別方法が記載されていて、setupを別functionで実装してそれを共通関数化にしました。
https://testing-library.com/docs/user-event/intro/

2023-02-14 08:53 UTC, undesicimo commented on package.json
> +    "@testing-library/user-event": "^14.4.3"
@hosht 
こちらのdependencies を、アップデートをしようとしたところ、無意識に `--save-dev
をつけてしまいました。申し訳ございません。
devDependenciesの場合、本番環境に含まれないことは分かりましたが、今回の実装に関しては問題ないでしょうか？

2023-02-14 09:42 UTC, anizozina reviewed
Board.test.tsxがないような 🤔

2023-02-14 09:46 UTC, moroball14 commented on src/components/Game.test.tsx
> +        expect(squares[0]).toHaveTextContent('X');
@undesicimo 

```
await user.click(squares[0]);
await user.click(squares[1]);
await user.click(squares[2]);
```

このclickした後の状態を検証しておくと、 `await user.click(gameStartHistory)` の挙動がわかりやすくなるので、追記した方が良いかもです 🤔

2023-02-14 09:46 UTC, moroball14 commented on src/components/Game.test.tsx
> +describe('Board component', () => {
must: Boardコンポーネントは、テストファイル分けましょう 👍

2023-02-14 09:46 UTC, moroball14 commented on src/components/Game.test.tsx
> +describe('Board component', () => {
Squareも同様です

2023-02-14 09:46 UTC, moroball14 commented on src/components/Game.test.tsx
> +        render(<Game />);
must: Boardコンポーネントのテストなので、Boardコンポーネントだけをrenderした方が良さそうです

2023-02-14 09:46 UTC, moroball14 commented on src/components/Game.test.tsx
> +        render(<Game />);
Squareも同様です

2023-02-14 09:50 UTC, hosht commented on package.json
> +    "@testing-library/user-event": "^14.4.3"
npmパッケージのベストプラクティスとして、本番環境に含まれるパッケージは少しでも減らして最終的なバンドルサイズを減らすというものがあります。
devDependenciesに書いたパッケージは`npm install --omit-dev`することで、本番環境でコードを実行するために不要なコードを除外できます。

テストと型の情報はその筆頭で、基本的にはdevDependenciesにまとめます

Example:
https://github.com/bitkey-service/workhub-web/blob/develop/package.json

2023-02-15 05:18 UTC, undesicimo commented on src/components/Game.test.tsx
> +        expect(squares[0]).toHaveTextContent('X');
@moroball14 
>追記した方が良いかもです

`このclickした後の状態` に対しての追加テストのことでしょうか？

2023-02-15 05:28 UTC, undesicimo commented
@hosht @anizozina @moroball14 
テストファイルをcomponentごとに分けました。
テスト実行時の結果出力は以下となります。

```
 PASS  src/components/Square.test.tsx
 PASS  src/components/Board.test.tsx
 PASS  src/components/Game.test.tsx
---------------------|---------|----------|---------|---------|-------------------
File                 | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
---------------------|---------|----------|---------|---------|-------------------
All files            |   81.96 |    94.11 |   68.18 |   81.66 |                   
 src                 |   33.33 |      100 |      50 |   33.33 |                   
  App.tsx            |       0 |      100 |       0 |       0 | 3-4               
  index.tsx          |       0 |      100 |     100 |       0 | 7-10              
  userEvent.tsx      |     100 |      100 |     100 |     100 |                   
 src/components      |    85.1 |    91.66 |   68.42 |    85.1 |                   
  Board.tsx          |   74.07 |       90 |   53.84 |   74.07 | 10,60-92          
  Game.tsx           |     100 |      100 |     100 |     100 |                   
  Square.tsx         |     100 |      100 |     100 |     100 |                   
 src/interfaces      |       0 |        0 |       0 |       0 |                   
  BoardProps.tsx     |       0 |        0 |       0 |       0 |                   
  SquareProps.ts     |       0 |        0 |       0 |       0 |                   
  ValueProps.ts      |       0 |        0 |       0 |       0 |                   
 src/utilities       |     100 |      100 |     100 |     100 |                   
  calculateWinner.ts |     100 |      100 |     100 |     100 |                   
---------------------|---------|----------|---------|---------|-------------------

Test Suites: 3 passed, 3 total
Tests:       10 passed, 10 total
Snapshots:   0 total
Time:        3.762 s
Ran all test suites matching /./i.

Active Filters: filename /./
 › Press c to clear filters.

```

2023-02-15 08:41 UTC, hosht approved these changes

2023-02-15 08:57 UTC, moroball14 commented on src/components/Game.test.tsx
> +        expect(squares[0]).toHaveTextContent('X');
@undesicimo 
> このclickした後の状態 に対してのテストを追加するの認識は合っていますか？

テストを追加する、が assertionを追加する、であればあっています！

2023-02-15 09:07 UTC, moroball14 commented on src/components/Board.test.tsx
> +                squares={['X', 'O', 'O', 'X', 'O', 'X', 'X']}
nitpick: squaresって必ず9個の配列だと思うので少し違和感ありますね。。ちょっとパッとリンクが出てこないですが、以下のように型指定したら良い気がするので試していただけると 🙏 （stringではないと思うので、正しい型を定義していただけると）

```
[string, string, string, string, string, string, string, string, string]
```

2023-02-15 09:07 UTC, moroball14 commented on src/components/Square.test.tsx
> +                }}
suggestion: 以下でも良きです

```suggestion
                onSquareClick={mockFunction}
```

2023-02-15 09:07 UTC, moroball14 commented on src/components/Square.test.tsx
> +    });
nitpick: 片方のテストケースだけでこのコンポーネントの挙動（渡されたvalueを表示する）は担保できていると思うので、片方だけにしましょう！

2023-02-16 01:01 UTC, undesicimo commented on src/components/Square.test.tsx
> +    });
以下のコミットにて、重複分のテストを削除しました。

https://github.com/undesicimo/react-typescript-tictactoe/pull/2/commits/2b46dc65dd24123dfabf2c1cacabb1545e49f963

2023-02-16 01:03 UTC, undesicimo commented on src/components/Board.test.tsx
> +                squares={['X', 'O', 'O', 'X', 'O', 'X', 'X']}
以下のコミットにて、型定義を実装しました。フォローありがとうございました！
https://github.com/undesicimo/react-typescript-tictactoe/pull/2/commits/17dd052a411d2c7873e27e5d290585a0fcf9b4cf

2023-02-16 01:05 UTC, undesicimo commented on src/components/Game.test.tsx
> +        expect(squares[0]).toHaveTextContent('X');
以下のコミットにて、クリック後の状態のassertions を追加しました。
https://github.com/undesicimo/react-typescript-tictactoe/pull/2/commits/c8cd250379f43d65d84870b416724e9476f01355

2023-02-16 02:01 UTC, moroball14 commented on src/components/Board.tsx
> +            nextSquares[i] =  'X';
nitpick: この空白は不要だと思うので消しましょう。（プロダクションコードでは、 [prettier](https://prettier.io/) というcode formatterを導入しているので、こういうことは起きないようになっています）

2023-02-16 02:01 UTC, moroball14 commented on src/components/Game.tsx
> +    const [history, setHistory] = useState<valuesProps[]>([intialHistory]);
nitpick: 結局これは履歴の集まり、みたいな感じだと思うので、historyではなくhistoriesでも良いかなって思います！

2023-02-16 02:01 UTC, moroball14 commented on src/components/Game.tsx
> +    const handlePlay = (nextSquares: valuesProps) => {
👍

2023-02-16 02:29 UTC, anizozina approved these changes
![LGTM](https://www.lgtm.app/p/vM-Z9Teb4)

2023-02-16 02:29 UTC, anizozina commented on src/components/Board.test.tsx
> +                //xIsNext is false の場合
nitpick:  
自明なのでコメント不要です〜！  
コメントをつけるときはここらへんが指標になるかも？チームの指針にも因るとは思いますが。。。

> Code comments are useful for several purposes. A code comment can…
> 
> - explain what a particular function does
> - explain something which might not be obvious to the reader
> - clarify your intention behind a certain line or block of code
> - serve as a reminder to change something in the future.

ref. https://www.codeconquest.com/advanced-programming-concepts/code-commenting/

2023-02-16 02:39 UTC, hosht commented on src/components/Board.test.tsx
> +                //xIsNext is false の場合
imo: これも一例ですがコメントはなぜそうしなかったのか書くようにしてますね

>コードには How
テストコードには What
コミットログには Why
コードコメントには Why not

ref. https://twitter.com/t_wada/status/904916106153828352

> explain something which might not be obvious to the reader
>explain what a particular function does

これはWhatなのでテストで書かれているべきで、

> clarify your intention behind a certain line or block of code

これはコミットログにするかWhy notとしてコメントすることがあり、

> serve as a reminder to change something in the future.

これはWhy notじゃないけど`TODO`や`FIXME`つけてコメントしますね

2023-02-16 02:58 UTC, undesicimo commented on src/components/Game.test.tsx
> +        expect(squares[0]).toHaveTextContent('X');
@moroball14 
以下のコミットにて、assertionsの再度修正を実装しました。
https://github.com/undesicimo/react-typescript-tictactoe/pull/2/commits/896cb53999870eadf7c212ff1b746692fa70d62f

2023-02-16 02:59 UTC, undesicimo commented on src/components/Game.tsx
> +    const [history, setHistory] = useState<valuesProps[]>([intialHistory]);
以下のコミットにて、変数命名の変更を行いました。
https://github.com/undesicimo/react-typescript-tictactoe/pull/2/commits/f4f1f51e1918885e010cbb8ffb5c7ceb61b5b772

2023-02-16 02:59 UTC, undesicimo commented on src/components/Board.tsx
> +            nextSquares[i] =  'X';
以下のコミットにて不要のスペースを削除しました。
https://github.com/undesicimo/react-typescript-tictactoe/pull/2/commits/f4f1f51e1918885e010cbb8ffb5c7ceb61b5b772

2023-02-17 01:29 UTC, moroball14 approved these changes
ちょっとコメントしていますが、LGTMです〜
あと、README.mdにテストの実行手順も書きましょう〜

2023-02-17 01:29 UTC, moroball14 commented on src/components/Board.test.tsx
> +import { getAllByRole, getRoles, screen } from '@testing-library/dom';
suggestion: 使っていない変数は削除していただけると

```suggestion
import { screen } from '@testing-library/dom';
```

2023-02-17 01:29 UTC, moroball14 commented on src/components/Board.test.tsx
> +                }}
suggestion: こちらでも良きかなーと！

```suggestion
                onPlay={mockFunction}
```

2023-02-17 01:29 UTC, moroball14 commented on src/components/Board.test.tsx
> +    it('should have O as next player after X ', () => {
```suggestion
    it('should have O as next player after X', () => {
```

2023-02-17 06:22 UTC, merged